# Logger settings
logger:
  # Path to the log file
  path: betterglobekey.log
  # Log file retention settings
  retain:
    # Number of days to retain log files
    days: 30
    # Number of log files to retain
    copies: 3

# Configuration options for double press of the Globe key
double_press:
  # Maximum time (in milliseconds) between first and second press to consider as a double press
  maximum_delay: 250

# Input sources configuration
#
# Each key-value pair within the 'input_sources' map represents a named collection of input sources.
# Single press of the Globe key cycles through input sources within the current collection.
# Double press of the Globe key switches between these collections.
#
# Example configuration:
# input_sources:
#   foo:
#     - com.apple.keylayout.US
#     - com.apple.keylayout.Russian
#   bar:
#     - com.apple.keylayout.Finnish
#     - com.apple.keylayout.Ukrainian-PC
#     - com.apple.inputmethod.Kotoeri.RomajiTyping.Japanese
input_sources: {}
