package config

import (
	"fmt"
	"os"

	"github.com/Serpentiel/betterglobekey/internal/domain/config"
	"gopkg.in/yaml.v3"
)

// Save validates cfg and writes it to path as a fresh, current-version
// configuration document, replacing any existing file. The standard header is
// prepended so the persisted file matches one generated by WriteDefault.
func Save(path string, cfg config.Config) error {
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("invalid config: %w", err)
	}

	data, err := yaml.Marshal(fromDomain(cfg))
	if err != nil {
		return fmt.Errorf("encoding config: %w", err)
	}

	//nolint:gosec // path is the user-provided config file
	if err := os.WriteFile(path, append([]byte(defaultHeader), data...), configFileMode); err != nil {
		return fmt.Errorf("writing config %q: %w", path, err)
	}

	return nil
}

// fromDomain converts the domain configuration model into the current on-disk schema.
func fromDomain(cfg config.Config) schemaV2 {
	hud := cfg.HUD

	var schema schemaV2

	schema.Version = currentVersion
	schema.Logger.Path = cfg.Logger.Path
	schema.Logger.Retention.Days = cfg.Logger.RetentionDays
	schema.Logger.Retention.Files = cfg.Logger.RetentionFiles
	schema.DoublePress.MaximumDelay = cfg.DoublePressMaxDelay.String()
	schema.HUD = &hud
	schema.Collections = make([]collectionV2, 0, len(cfg.Collections))

	for _, collection := range cfg.Collections {
		schema.Collections = append(
			schema.Collections,
			collectionV2{Name: collection.Name, Sources: collection.Sources},
		)
	}

	return schema
}
