name: Changelog Enforcer

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  changelog-enforcer:
    runs-on: ubuntu-latest
    if: ((github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip workflows')) || github.event_name == 'push') && github.actor != 'dependabot[bot]'
    steps:
      - uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: no changelog
